#!/usr/bin/env sh

MNT_DIR="/mnt/image"
modprobe loop
modprobe ext4
LOOP_PART=`losetup --show -f ${IMAGE}`

mkdir ${MNT_DIR}
mount ${LOOP_PART}p2 ${MNT_DIR}
truncate -s 0 ${MNT_DIR}/etc/ld.so.preload
sed -i 2,3d ${MNT_DIR}/etc/fstab
sync
umount ${MNT_DIR}
losetup -d ${LOOP_PART}
